"""knowledge chat: conversations, messages, pinned snippets

Revision ID: 7bd7549b7de8
Revises: c61405d08dad
Create Date: 2026-07-17 14:53:54.829290+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bd7549b7de8'
down_revision: str | None = 'c61405d08dad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_conversation',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_conversation_estate_id'), 'qa_conversation', ['estate_id'], unique=False)
    op.create_table('qa_message',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sources_cited', sa.JSON(), nullable=True),
    sa.Column('related_sources', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['qa_conversation.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_message_conversation_id'), 'qa_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_qa_message_estate_id'), 'qa_message', ['estate_id'], unique=False)
    op.create_table('qa_pinned_snippet',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_doc_id', sa.Uuid(), nullable=True),
    sa.Column('doc_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['qa_conversation.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['knowledge_doc_id'], ['knowledge_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_pinned_snippet_conversation_id'), 'qa_pinned_snippet', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_qa_pinned_snippet_estate_id'), 'qa_pinned_snippet', ['estate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_pinned_snippet_estate_id'), table_name='qa_pinned_snippet')
    op.drop_index(op.f('ix_qa_pinned_snippet_conversation_id'), table_name='qa_pinned_snippet')
    op.drop_table('qa_pinned_snippet')
    op.drop_index(op.f('ix_qa_message_estate_id'), table_name='qa_message')
    op.drop_index(op.f('ix_qa_message_conversation_id'), table_name='qa_message')
    op.drop_table('qa_message')
    op.drop_index(op.f('ix_qa_conversation_estate_id'), table_name='qa_conversation')
    op.drop_table('qa_conversation')
    # ### end Alembic commands ###
