"""initial schema: 29 tables per build contract section 6

Revision ID: c61405d08dad
Revises: 
Create Date: 2026-07-06 12:36:28.659568+00:00

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c61405d08dad'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before the knowledge_chunk embedding column
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estate',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('constants_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nrb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rnrb', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('taper_threshold', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tnrb_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('trnrb_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('residence_to_descendants_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('charity_share_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('claims_rnrb', sa.Boolean(), nullable=True),
    sa.Column('gifts_with_reservation', sa.Boolean(), nullable=True),
    sa.Column('foreign_assets_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('trust_property_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('specified_transfers_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_tax',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('tax_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estate_complex', sa.Boolean(), nullable=True),
    sa.Column('cgt_disposals', sa.JSON(), nullable=False),
    sa.Column('cgt_60day_deadlines', sa.JSON(), nullable=False),
    sa.Column('isa_exemption_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_tax_estate_id'), 'admin_tax', ['estate_id'], unique=False)
    op.create_index(op.f('ix_admin_tax_tax_year'), 'admin_tax', ['tax_year'], unique=False)
    op.create_table('approval',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('entity_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_draft_kind'), 'approval', ['draft_kind'], unique=False)
    op.create_index(op.f('ix_approval_entity_ref'), 'approval', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_approval_estate_id'), 'approval', ['estate_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_actor'), 'audit_event', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_event_entity'), 'audit_event', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_event_estate_id'), 'audit_event', ['estate_id'], unique=False)
    op.create_table('contact',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('bank', 'nsandi', 'insurer', 'pension', 'utility', 'telecom', 'tv_licensing', 'streaming', 'council', 'hmrc', 'probate_registry', 'solicitor', 'accountant', 'valuer', 'registrar', 'gp', 'dentist', 'optician', 'employer', 'landlord', 'care_agency', 'beneficiary', 'gift_recipient', 'creditor', 'debtor', 'executor', 'membership', 'other', name='contactcategory', native_enum=False, length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('holds_or_handles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notify_required', sa.Boolean(), nullable=False),
    sa.Column('notification_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notified_date', sa.Date(), nullable=True),
    sa.Column('notified_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_category'), 'contact', ['category'], unique=False)
    op.create_index(op.f('ix_contact_estate_id'), 'contact', ['estate_id'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_table('creditor_notice',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('gazette_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gazette_date', sa.Date(), nullable=True),
    sa.Column('local_paper', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('claim_deadline', sa.Date(), nullable=True),
    sa.Column('safe_to_distribute', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditor_notice_estate_id'), 'creditor_notice', ['estate_id'], unique=False)
    op.create_table('deadline',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('derived_date', sa.Date(), nullable=True),
    sa.Column('reminders', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_estate_id'), 'deadline', ['estate_id'], unique=False)
    op.create_index(op.f('ix_deadline_type'), 'deadline', ['type'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('options_considered', sa.JSON(), nullable=True),
    sa.Column('agreed_by', sa.JSON(), nullable=False),
    sa.Column('made_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_estate_id'), 'decision', ['estate_id'], unique=False)
    op.create_index(op.f('ix_decision_title'), 'decision', ['title'], unique=False)
    op.create_table('digital_item',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('login_known', sa.Boolean(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recurring_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_item_estate_id'), 'digital_item', ['estate_id'], unique=False)
    op.create_index(op.f('ix_digital_item_service'), 'digital_item', ['service'], unique=False)
    op.create_table('document',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('access_roles', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('executor_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_estate_id'), 'document', ['estate_id'], unique=False)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_table('iht_assessment',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('constants_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iht_assessment_estate_id'), 'iht_assessment', ['estate_id'], unique=False)
    op.create_table('knowledge_doc',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetch_date', sa.Date(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('licence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_file_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_doc_estate_id'), 'knowledge_doc', ['estate_id'], unique=False)
    op.create_index(op.f('ix_knowledge_doc_form_code'), 'knowledge_doc', ['form_code'], unique=False)
    op.create_index(op.f('ix_knowledge_doc_source_url'), 'knowledge_doc', ['source_url'], unique=False)
    op.create_index(op.f('ix_knowledge_doc_title'), 'knowledge_doc', ['title'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('from_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_id', sa.Uuid(), nullable=False),
    sa.Column('to_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_estate_id'), 'link', ['estate_id'], unique=False)
    op.create_index(op.f('ix_link_from_id'), 'link', ['from_id'], unique=False)
    op.create_index(op.f('ix_link_from_type'), 'link', ['from_type'], unique=False)
    op.create_index(op.f('ix_link_to_id'), 'link', ['to_id'], unique=False)
    op.create_index(op.f('ix_link_to_type'), 'link', ['to_type'], unique=False)
    op.create_table('notification',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_estate_id'), 'notification', ['estate_id'], unique=False)
    op.create_index(op.f('ix_notification_event_type'), 'notification', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('asset',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('holder_contact_id', sa.Uuid(), nullable=True),
    sa.Column('account_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ownership', sa.Enum('sole', 'joint_tenants', 'tenants_in_common', name='ownershiptype', native_enum=False, length=64), nullable=False),
    sa.Column('tic_share_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('dod_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('value_basis', sa.Enum('estimate', 'confirmed', name='valuebasis', native_enum=False, length=64), nullable=False),
    sa.Column('valuation_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('current_or_realised_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('realised_date', sa.Date(), nullable=True),
    sa.Column('income_since_death', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iht_schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rnrb_qualifying', sa.Boolean(), nullable=False),
    sa.Column('passes_outside_estate', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['holder_contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_category'), 'asset', ['category'], unique=False)
    op.create_index(op.f('ix_asset_estate_id'), 'asset', ['estate_id'], unique=False)
    op.create_index(op.f('ix_asset_holder_contact_id'), 'asset', ['holder_contact_id'], unique=False)
    op.create_table('beneficiary_legacy',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_contact_id', sa.Uuid(), nullable=False),
    sa.Column('legacy_type', sa.Enum('pecuniary', 'specific', 'residuary', name='legacytype', native_enum=False, length=64), nullable=False),
    sa.Column('amount_or_share', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('exempt_or_chargeable', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_bearing', sa.Boolean(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_legacy_beneficiary_contact_id'), 'beneficiary_legacy', ['beneficiary_contact_id'], unique=False)
    op.create_index(op.f('ix_beneficiary_legacy_estate_id'), 'beneficiary_legacy', ['estate_id'], unique=False)
    op.create_index(op.f('ix_beneficiary_legacy_legacy_type'), 'beneficiary_legacy', ['legacy_type'], unique=False)
    op.create_table('contact_interaction',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('by_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_interaction_contact_id'), 'contact_interaction', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_interaction_estate_id'), 'contact_interaction', ['estate_id'], unique=False)
    op.create_table('cost',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('paid_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reimbursable', sa.Boolean(), nullable=False),
    sa.Column('reimbursed', sa.Boolean(), nullable=False),
    sa.Column('reimbursed_date', sa.Date(), nullable=True),
    sa.Column('iht_treatment', sa.Enum('funeral_deductible', 'admin_not_deductible', name='ihttreatment', native_enum=False, length=64), nullable=False),
    sa.Column('receipt_document_id', sa.Uuid(), nullable=True),
    sa.Column('executor_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['receipt_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_category'), 'cost', ['category'], unique=False)
    op.create_index(op.f('ix_cost_estate_id'), 'cost', ['estate_id'], unique=False)
    op.create_index(op.f('ix_cost_receipt_document_id'), 'cost', ['receipt_document_id'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_doc_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['knowledge_doc_id'], ['knowledge_doc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_estate_id'), 'knowledge_chunk', ['estate_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_knowledge_doc_id'), 'knowledge_chunk', ['knowledge_doc_id'], unique=False)
    op.create_table('liability',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creditor_contact_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('as_at_date', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iht_deductible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creditor_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liability_creditor_contact_id'), 'liability', ['creditor_contact_id'], unique=False)
    op.create_index(op.f('ix_liability_estate_id'), 'liability', ['estate_id'], unique=False)
    op.create_index(op.f('ix_liability_type'), 'liability', ['type'], unique=False)
    op.create_table('notice_claim',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('creditor_notice_id', sa.Uuid(), nullable=False),
    sa.Column('claimant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['creditor_notice_id'], ['creditor_notice.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_claim_creditor_notice_id'), 'notice_claim', ['creditor_notice_id'], unique=False)
    op.create_index(op.f('ix_notice_claim_estate_id'), 'notice_claim', ['estate_id'], unique=False)
    op.create_table('process_step',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadline.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_step_deadline_id'), 'process_step', ['deadline_id'], unique=False)
    op.create_index(op.f('ix_process_step_estate_id'), 'process_step', ['estate_id'], unique=False)
    op.create_index(op.f('ix_process_step_order'), 'process_step', ['order'], unique=False)
    op.create_table('creditor',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('creditor_contact_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_claimed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_agreed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_from_asset_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creditor_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['paid_from_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditor_creditor_contact_id'), 'creditor', ['creditor_contact_id'], unique=False)
    op.create_index(op.f('ix_creditor_estate_id'), 'creditor', ['estate_id'], unique=False)
    op.create_index(op.f('ix_creditor_paid_from_asset_id'), 'creditor', ['paid_from_asset_id'], unique=False)
    op.create_index(op.f('ix_creditor_type'), 'creditor', ['type'], unique=False)
    op.create_table('debtor',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('source_contact_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_expected', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_received', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_into_asset_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['received_into_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['source_contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debtor_estate_id'), 'debtor', ['estate_id'], unique=False)
    op.create_index(op.f('ix_debtor_received_into_asset_id'), 'debtor', ['received_into_asset_id'], unique=False)
    op.create_index(op.f('ix_debtor_source_contact_id'), 'debtor', ['source_contact_id'], unique=False)
    op.create_index(op.f('ix_debtor_type'), 'debtor', ['type'], unique=False)
    op.create_table('distribution',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_legacy_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_legacy_id'], ['beneficiary_legacy.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_beneficiary_legacy_id'), 'distribution', ['beneficiary_legacy_id'], unique=False)
    op.create_index(op.f('ix_distribution_estate_id'), 'distribution', ['estate_id'], unique=False)
    op.create_table('relief',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('relief_type', sa.Enum('iht35', 'iht38', 'rnrb_downsizing', 'bpr_apr', name='relieftype', native_enum=False, length=64), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('probate_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sale_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('window_deadline', sa.Date(), nullable=True),
    sa.Column('potential_reclaim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relief_asset_id'), 'relief', ['asset_id'], unique=False)
    op.create_index(op.f('ix_relief_estate_id'), 'relief', ['estate_id'], unique=False)
    op.create_index(op.f('ix_relief_relief_type'), 'relief', ['relief_type'], unique=False)
    op.create_table('task',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignees', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('blocked_by', sa.JSON(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('process_step_id', sa.Uuid(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reminder', sa.Date(), nullable=True),
    sa.Column('executor_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['process_step_id'], ['process_step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_estate_id'), 'task', ['estate_id'], unique=False)
    op.create_index(op.f('ix_task_process_step_id'), 'task', ['process_step_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    op.create_table('valuation_event',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('basis', sa.Enum('estimate', 'confirmed', name='valuebasis', native_enum=False, length=64), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_event_asset_id'), 'valuation_event', ['asset_id'], unique=False)
    op.create_index(op.f('ix_valuation_event_estate_id'), 'valuation_event', ['estate_id'], unique=False)
    op.create_table('task_comment',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comment_estate_id'), 'task_comment', ['estate_id'], unique=False)
    op.create_index(op.f('ix_task_comment_task_id'), 'task_comment', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_comment_task_id'), table_name='task_comment')
    op.drop_index(op.f('ix_task_comment_estate_id'), table_name='task_comment')
    op.drop_table('task_comment')
    op.drop_index(op.f('ix_valuation_event_estate_id'), table_name='valuation_event')
    op.drop_index(op.f('ix_valuation_event_asset_id'), table_name='valuation_event')
    op.drop_table('valuation_event')
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_process_step_id'), table_name='task')
    op.drop_index(op.f('ix_task_estate_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_relief_relief_type'), table_name='relief')
    op.drop_index(op.f('ix_relief_estate_id'), table_name='relief')
    op.drop_index(op.f('ix_relief_asset_id'), table_name='relief')
    op.drop_table('relief')
    op.drop_index(op.f('ix_distribution_estate_id'), table_name='distribution')
    op.drop_index(op.f('ix_distribution_beneficiary_legacy_id'), table_name='distribution')
    op.drop_table('distribution')
    op.drop_index(op.f('ix_debtor_type'), table_name='debtor')
    op.drop_index(op.f('ix_debtor_source_contact_id'), table_name='debtor')
    op.drop_index(op.f('ix_debtor_received_into_asset_id'), table_name='debtor')
    op.drop_index(op.f('ix_debtor_estate_id'), table_name='debtor')
    op.drop_table('debtor')
    op.drop_index(op.f('ix_creditor_type'), table_name='creditor')
    op.drop_index(op.f('ix_creditor_paid_from_asset_id'), table_name='creditor')
    op.drop_index(op.f('ix_creditor_estate_id'), table_name='creditor')
    op.drop_index(op.f('ix_creditor_creditor_contact_id'), table_name='creditor')
    op.drop_table('creditor')
    op.drop_index(op.f('ix_process_step_order'), table_name='process_step')
    op.drop_index(op.f('ix_process_step_estate_id'), table_name='process_step')
    op.drop_index(op.f('ix_process_step_deadline_id'), table_name='process_step')
    op.drop_table('process_step')
    op.drop_index(op.f('ix_notice_claim_estate_id'), table_name='notice_claim')
    op.drop_index(op.f('ix_notice_claim_creditor_notice_id'), table_name='notice_claim')
    op.drop_table('notice_claim')
    op.drop_index(op.f('ix_liability_type'), table_name='liability')
    op.drop_index(op.f('ix_liability_estate_id'), table_name='liability')
    op.drop_index(op.f('ix_liability_creditor_contact_id'), table_name='liability')
    op.drop_table('liability')
    op.drop_index(op.f('ix_knowledge_chunk_knowledge_doc_id'), table_name='knowledge_chunk')
    op.drop_index(op.f('ix_knowledge_chunk_estate_id'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index(op.f('ix_cost_receipt_document_id'), table_name='cost')
    op.drop_index(op.f('ix_cost_estate_id'), table_name='cost')
    op.drop_index(op.f('ix_cost_category'), table_name='cost')
    op.drop_table('cost')
    op.drop_index(op.f('ix_contact_interaction_estate_id'), table_name='contact_interaction')
    op.drop_index(op.f('ix_contact_interaction_contact_id'), table_name='contact_interaction')
    op.drop_table('contact_interaction')
    op.drop_index(op.f('ix_beneficiary_legacy_legacy_type'), table_name='beneficiary_legacy')
    op.drop_index(op.f('ix_beneficiary_legacy_estate_id'), table_name='beneficiary_legacy')
    op.drop_index(op.f('ix_beneficiary_legacy_beneficiary_contact_id'), table_name='beneficiary_legacy')
    op.drop_table('beneficiary_legacy')
    op.drop_index(op.f('ix_asset_holder_contact_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_estate_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_category'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_event_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_estate_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_link_to_type'), table_name='link')
    op.drop_index(op.f('ix_link_to_id'), table_name='link')
    op.drop_index(op.f('ix_link_from_type'), table_name='link')
    op.drop_index(op.f('ix_link_from_id'), table_name='link')
    op.drop_index(op.f('ix_link_estate_id'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_knowledge_doc_title'), table_name='knowledge_doc')
    op.drop_index(op.f('ix_knowledge_doc_source_url'), table_name='knowledge_doc')
    op.drop_index(op.f('ix_knowledge_doc_form_code'), table_name='knowledge_doc')
    op.drop_index(op.f('ix_knowledge_doc_estate_id'), table_name='knowledge_doc')
    op.drop_table('knowledge_doc')
    op.drop_index(op.f('ix_iht_assessment_estate_id'), table_name='iht_assessment')
    op.drop_table('iht_assessment')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_estate_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_digital_item_service'), table_name='digital_item')
    op.drop_index(op.f('ix_digital_item_estate_id'), table_name='digital_item')
    op.drop_table('digital_item')
    op.drop_index(op.f('ix_decision_title'), table_name='decision')
    op.drop_index(op.f('ix_decision_estate_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_deadline_type'), table_name='deadline')
    op.drop_index(op.f('ix_deadline_estate_id'), table_name='deadline')
    op.drop_table('deadline')
    op.drop_index(op.f('ix_creditor_notice_estate_id'), table_name='creditor_notice')
    op.drop_table('creditor_notice')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_estate_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_category'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_audit_event_estate_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_entity'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_approval_estate_id'), table_name='approval')
    op.drop_index(op.f('ix_approval_entity_ref'), table_name='approval')
    op.drop_index(op.f('ix_approval_draft_kind'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_admin_tax_tax_year'), table_name='admin_tax')
    op.drop_index(op.f('ix_admin_tax_estate_id'), table_name='admin_tax')
    op.drop_table('admin_tax')
    op.drop_table('estate')
    # ### end Alembic commands ###
